/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'account-settings': RouteRecordInfo<'account-settings', '/account-settings', Record<never, never>, Record<never, never>>,
    'anagrafiche': RouteRecordInfo<'anagrafiche', '/anagrafiche', Record<never, never>, Record<never, never>>,
    'anagrafiche-id': RouteRecordInfo<'anagrafiche-id', '/anagrafiche/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'anagrafiche-modifica-id': RouteRecordInfo<'anagrafiche-modifica-id', '/anagrafiche/modifica-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'anagrafiche-nuovo': RouteRecordInfo<'anagrafiche-nuovo', '/anagrafiche/nuovo', Record<never, never>, Record<never, never>>,
    'auth-microsoft-callback': RouteRecordInfo<'auth-microsoft-callback', '/auth/microsoft-callback', Record<never, never>, Record<never, never>>,
    'contatti': RouteRecordInfo<'contatti', '/contatti', Record<never, never>, Record<never, never>>,
    'contatti-id': RouteRecordInfo<'contatti-id', '/contatti/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contatti-modifica-id': RouteRecordInfo<'contatti-modifica-id', '/contatti/modifica-:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'contatti-nuovo': RouteRecordInfo<'contatti-nuovo', '/contatti/nuovo', Record<never, never>, Record<never, never>>,
    'dashboard': RouteRecordInfo<'dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'forgot-password': RouteRecordInfo<'forgot-password', '/forgot-password', Record<never, never>, Record<never, never>>,
    'indirizzi': RouteRecordInfo<'indirizzi', '/indirizzi', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'notifiche': RouteRecordInfo<'notifiche', '/notifiche', Record<never, never>, Record<never, never>>,
    'reset-password': RouteRecordInfo<'reset-password', '/reset-password', Record<never, never>, Record<never, never>>,
  }
}
